---
title: Hagura - Light!
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: "/hagura"
email: your@email.com
highlighter: rouge
markdown: kramdown
analytics: UA-83979019-1
disqus-shortname: webjeda-demo
compress_html:
  clippings:
  - html
  - div
  - p
  - ul
  - td
  - h1
  - h2
  - h3
  - h4
  - link
  - meta
  - footer
  - nav
  - img
  - header
  - hr
  - br
  - head
  - style
  - li
  - ul
  - ol
  - time
  - main
  - script
  - title
  comments:
  - "<!-- "
  - " -->"
  endings:
  - all
  ignore:
    envs:
    - local
  blanklines: false
  profile: false
  startings: []
sass:
  style: compressed
exclude:
- README.md
gems:
- jekyll-seo-tag
- jekyll-paginate
