---
title: Indexmod Alterpedia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
description: Indexmod Alterpedia â€” is an alternative wiki encyclopedia with pretty
  syntax
include:
- ".htaccess"
show_sidebar: false
show_downloads: false
show_title: false
show_description: false
google_analytics: 'UA-111762431-1

'
theme: jekyll-theme-minimal
