---
title: Your awesome title
timezone: UTC
collections:
  uploads:
    title: GHJ
    output: true
  posts:
    title: Posts
    output: true
author: GitHub User
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
twitter_username: jekyllrb
github_username: jekyll
minima:
  date_format: "%b %-d, %Y"
markdown: kramdown
theme: minima
exclude:
- Gemfile
- Gemfile.lock
